In [39]:
import pandas as pd
from sklearn import tree
from sklearn import preprocessing
from sklearn import ensemble
from sklearn import feature_extraction
from sklearn.cross_validation import cross_val_score
import numpy as np

In [13]:
df=pd.read_csv('train.csv',delimiter=',')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

Some Ages missing, some embarked missing

In [31]:
df['nameLength']=df.Name.apply(lambda x:len(x.split()))

In [25]:
df.Sex=df.Sex.apply(lambda x: {'male':0,'female':1}[x])
# Binarise sexes

In [14]:
set(df.Embarked.values)

{nan, 'C', 'Q', 'S'}

In [16]:
df.Embarked=df.Embarked.apply(lambda x: {'C':0,'Q':1,'S':2}.get(x))
# Binarise embarked

In [19]:
df.Embarked.value_counts()

2    646
0    168
1     77
dtype: int64

In [18]:
df.Embarked[df.Embarked.isnull()]=2
# Assign most common value

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [44]:
enc = preprocessing.OneHotEncoder()

In [49]:
enc.fit_transform(np.vstack(df.Embarked.values)).toarray()

array([[ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [22]:
clf=tree.DecisionTreeClassifier()

In [40]:
clf=ensemble.RandomForestClassifier()

In [32]:
for n,c in enumerate(df.columns):
    print n,c

0 PassengerId
1 Survived
2 Pclass
3 Name
4 Sex
5 Age
6 SibSp
7 Parch
8 Ticket
9 Fare
10 Cabin
11 Embarked
12 nameLength


In [41]:
clf.fit(df.icol([2,4,6,7,9,11,12]),df.Survived)

RandomForestClassifier(bootstrap=True, compute_importances=None,
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_density=None, min_samples_leaf=1,
            min_samples_split=2, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0)

In [42]:
clf.feature_importances_

array([ 0.09741682,  0.27659029,  0.05533691,  0.062103  ,  0.35571343,
        0.04455823,  0.10828131])

In [43]:
cross_val_score(clf,df.icol([2,4,6,7,9,11,12]),df.Survived)

array([ 0.75757576,  0.79124579,  0.77104377])

Try random forests